### ISSUE TITLE
Unable to find css "iframe#scenario-frame"

### ISSUE THREAD

**Issue by searls** [stepful/cyperful#2]
Ran into this issue running a single test (as suggested in the README). 

What I experienced:

* Roughly 30 second startup time (usually a few seconds)
* Test opened to the first `visit`ed page
* Then the Cyperful runner launched
* Then nothing happened
* Clicking the play button resulted in the first `visit`ed page being shown again

Trace:

```
# Running:

Capybara starting Puma...
* Version 6.4.2, codename: The Eagle of Durango
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:49232
* Listening on http://[::1]:49232
Setting up Cyperful for: ProgramAdminTest#test_make_a_program
Cyperful server started: http://localhost:3004
Found 42 steps:
  1.  visit: 6:4
  2.  click_on: 8:4
  3.  click_on: 9:4
  4.  click_on: 10:4
  5.  fill_in: 11:4
  6.  fill_in: 12:4
  7.  attach_file: 13:4
  8.  fill_in: 14:4
  9.  fill_in: 15:4
 10.  fill_in: 16:4
 11.  check: 17:4
 12.  click_on: 18:4
 13.  assert_text: 19:4
 14.  click_on: 21:4
 15.  click_on: 22:4
 16.  click_on: 23:4
 17.  fill_in: 24:4
 18.  fill_in: 25:4
 19.  fill_in: 26:4
 20.  check: 27:4
 21.  check: 28:4
 22.  attach_file: 30:4
 23.  attach_file: 31:4
 24.  select: 32:4
 25.  click_on: 33:4
 26.  assert_text: 34:4
 27.  click_on: 36:4
 28.  click_on: 37:4
 29.  click: 38:4
 30.  fill_in: 39:4
 31.  attach_file: 40:4
 32.  attach_file: 41:4
 33.  check: 42:4
 34.  check: 43:4
 35.  check: 44:4
 36.  select: 45:4
 37.  fill_in: 46:4
 38.  click: 48:4
 39.  select: 52:6
 40.  click: 55:4
 41.  fill_in: 56:4
 42.  first: 57:11

Driving iframe...
Driving iframe...


Test failed with error:
Unable to find css "iframe#scenario-frame"
/Users/justin/code/searls/grog/test/system/program_admin_test.rb:5:in `test_make_a_program'
/Users/justin/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/minitest-5.21.2/lib/minitest/test.rb:94:in `block (3 levels) in run'
/Users/justin/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/minitest-5.21.2/lib/minitest/test.rb:191:in `capture_exceptions'
/Users/justin/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/minitest-5.21.2/lib/minitest/test.rb:89:in `block (2 levels) in run'
/Users/justin/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/minitest-5.21.2/lib/minitest.rb:303:in `time_it'
/Users/justin/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/minitest-5.21.2/lib/minitest/test.rb:88:in `block in run'
Cyperful teardown complete. Waiting for command...
```

**Comment by wyattades** [comment]
@searls do you want to try the latest version? I have a feeling it was something about the browser + drive (chrome + selenium), which we now have a check for

**Comment by wyattades** [comment]
Going to close this as stale, but please let me know if you have more details
